### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by pedronveloso** [aalices/RajawaliNewVuforia#1]
Hi,

I've forked this and I've tested with the example on the main Rajawali repo. Got it working, it recognizes the stones sample, but when I move the camera vertically the model goes the opposite direction. I was wondering if you could share your example code for this, or if you have an idea on how I could fix it.

**Comment by aalices** [comment]
What is your screen orientation?

**Comment by pedronveloso** [comment]
Landscape. I did try to change that, and played with Landscape-reverse, but same result. I don't think the problem comes from that.

**Comment by aalices** [comment]
The rendered camera preview is okay but the model goes the other way, right? I haven't been working with the libs quite a long time but in `RajawaliVuforiaRenderer` there is a method `TransformPositionAndOrientation` - maybe you have to change the signs of x and y

**Comment by pedronveloso** [comment]
Thank you for the tip, I'll try to play around with those values.
